// <auto-generated />
namespace _12_10_16_production_ref_portal_api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class gameplayer1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gameplayer1));
        
        string IMigrationMetadata.Id
        {
            get { return "201610121050181_gameplayer1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
